### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-java#268]
```
com.uber.jaeger.samplers.RemoteControlledSamplerTest > testUpdatePerOperationSamplerUpdatesExistingPerOperationSampler FAILED
    org.mockito.exceptions.verification.TooLittleActualInvocations: 
    perOperationSampler.update(
        Mock for OperationSamplingParameters, hashCode: 115078806
    );
    Wanted 2 times:
    -> at com.uber.jaeger.samplers.PerOperationSampler.update(PerOperationSampler.java:56)
    But was 1 time:
    -> at com.uber.jaeger.samplers.PerOperationSampler.update(PerOperationSampler.java:56)
        at com.uber.jaeger.samplers.PerOperationSampler.update(PerOperationSampler.java:56)
        at com.uber.jaeger.samplers.RemoteControlledSamplerTest.testUpdatePerOperationSamplerUpdatesExistingPerOperationSampler(RemoteControlledSamplerTest.java:113)
```

**Comment by yurishkuro** [comment]
Full screen of recent `master` builds with no failures, so perhaps this is not an issue any more.
