### ISSUE TITLE
Spans not showing up in Jaeger UI

### ISSUE THREAD

**Issue by vibhory2j** [jaegertracing/jaeger-client-java#275]
I need some help in debugging an issue. I'm trying to instrument kairosDB using jaeger core and opentracing libraries. Below is the output of application logs. The application is running as part of docker compose. I can spans reported by other services from compose.

1. There is an exception once after tracer is initialized.
2. As per logs the span is reported. However, I'm unable to see them Jaeger UI.

16:24:52.285 [qtp1243102466-39] INFO  [LoggingReporter.java:50] - Span reported: ee6cb36789e6d617:ee6cb36789e6d617:0:1 - putData
Exception in thread "jaeger.RemoteReporter-QueueProcessor" java.lang.NoClassDefFoundError: org/apache/thrift/scheme/StandardScheme
	at com.uber.jaeger.thriftjava.Process.<clinit>(Process.java:46)
	at com.uber.jaeger.senders.ThriftSender.append(ThriftSender.java:68)
	at com.uber.jaeger.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:150)
	at com.uber.jaeger.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:183)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.thrift.scheme.StandardScheme
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
16:25:00.025 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: d85b308455212019:d85b308455212019:0:1 - putData
16:25:00.047 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: ab9ddc6d1e019f63:ab9ddc6d1e019f63:0:1 - putData
16:25:00.054 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: 3283a03f2b5b9e53:3283a03f2b5b9e53:0:1 - putData
16:25:00.060 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: bb8b59da629a4533:bb8b59da629a4533:0:1 - putData
16:25:00.094 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: 251b3103ffb3a979:251b3103ffb3a979:0:1 - putData
16:25:00.108 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: d37c19ffc3ccd0b1:d37c19ffc3ccd0b1:0:1 - putData
16:25:00.125 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: 7214f0e8e931f70e:7214f0e8e931f70e:0:1 - putData
16:25:00.141 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: 9689363b16329906:9689363b16329906:0:1 - putData
16:25:00.148 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: a0eb8df80704afb1:a0eb8df80704afb1:0:1 - putData
16:25:00.173 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: 884c526f61cdb996:884c526f61cdb996:0:1 - putData
16:25:00.193 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: 3a579fed8287892b:3a579fed8287892b:0:1 - putData
16:25:00.216 [QuartzScheduler_Worker-3] INFO  [LoggingReporter.java:50] - Span reported: a51c3cb17e2f84ef:a51c3cb17e2f84ef:0:1 - putData
16:25:07.167 [qtp1243102466-38] INFO  [LoggingReporter.java:50] - Span reported: a044ff84fd2edfc:a044ff84fd2edfc:0:1 - putData
16:25:22.248 [qtp1243102466-38] INFO  [LoggingReporter.java:50] - Span reported: 5d468cad74d9e64f:5d468cad74d9e64f:0:1 - putData

Any idea what is wrong here.

Thanks in advance for help.

**Comment by vibhory2j** [comment]
Was a problem with thrift library.
