### ISSUE TITLE
UdpSender broken

### ISSUE THREAD

**Issue by milenkovicm** [jaegertracing/jaeger-client-java#328]
Hi all, 
`com.uber.jaeger.senders.UdpSender` I believe is broken cause of two major problems
 - it does not respect `maxPacketSize` constructor parameter. `UdpSender` extends `ThriftSender` but apparently not much of the parent class is used
- if there is exception`at com.uber.jaeger.senders.UdpSender.send(UdpSender.java:60)` it will fail to flush the buffer.  As seen in 

```
org.apache.thrift.transport.TTransportException: Message size too large: 1 > 65000
	at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.write(ThriftUdpTransport.java:139)
	at org.apache.thrift.transport.TTransport.write(TTransport.java:107)
	at org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:482)
	at org.apache.thrift.protocol.TCompactProtocol.writeMessageBegin(TCompactProtocol.java:198)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62)
	at com.uber.jaeger.agent.thrift.Agent$Client.send_emitBatch(Agent.java:97)
	at com.uber.jaeger.agent.thrift.Agent$Client.emitBatch(Agent.java:90)
	at com.uber.jaeger.senders.UdpSender.send(UdpSender.java:60)
	at kamon.jaeger.JaegerClient.sendSpans(JaegerReporter.scala:77)
	at kamon.jaeger.JaegerReporter.reportSpans(JaegerReporter.scala:66)
	at kamon.ReporterRegistry$Default$SpanReporterTicker.$anonfun$run$9(ReporterRegistry.scala:384)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at kamon.ReporterRegistry$Default$SpanReporterTicker.$anonfun$run$8(ReporterRegistry.scala:384)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:60)
	at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at kamon.scala.instrumentation.FutureInstrumentation.$anonfun$aroundExecution$1(FutureInstrumentation.scala:46)
	at kamon.Kamon$.withContext(Kamon.scala:120)
	at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:46)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
in case on exception `org.apache.thrift.TServiceClient.sendBase()` will never execute `this.oprot_.getTransport().flush();`

the easy hack would be to flush after each `emitBatch`

```
  @Override
  public void send(Process process, List<com.uber.jaeger.thriftjava.Span> spans) throws TException {
  try {
    agentClient.emitBatch(new Batch(process, spans));
  } finally {
   udpTransport.flush()
  }
  }
```
this approach may create invalid messages, as partial messages could end up in the sending buffer.

looks like that previous implementation using `ThriftSender` had all corner cases covered.

**Comment by chandresh-pancholi** [comment]
Is this issue still open?
I have made changes. If it's open, I will raise the PR.

**Comment by jpkrohling** [comment]
@chandresh-pancholi a great first step would be to come up with unit tests based on @milenkovicm's description.
