### ISSUE TITLE
Tracerresolver fat jar request 

### ISSUE THREAD

**Issue by malafeev** [jaegertracing/jaeger-client-java#332]
To use tracerresolver with Linkerd instrumentation it is required to put tracerresolver jar with  all transitive dependencies in a `plugins` folder.
But finding all transitive dependencies is a pain.
Having fat jar would help a lot.

**Comment by pavolloffay** [comment]
Would something like this help? 
`mvn dependency:get -Dartifact=com.uber.jaeger:jaeger-core:0.23.0:pom -Ddest=.`
`mvn org.apache.maven.plugins:maven-dependency-plugin:2.7:copy-dependencies -f  jaeger-core-0.23.0.pom -DincludeScope=compile  -DoutputDirectory=.`

**Comment by malafeev** [comment]
looks like a solution!

**Comment by malafeev** [comment]
thank you @pavolloffay 
problem that I cannot use jaeger-thrift because application uses old thrift version (0.5)
I tried to use shaded jar: jaeger-thrift-0.24.0-thrift92.jar
But I get exception:
```
java.lang.NoSuchMethodError: com.uber.jaeger.agent.thrift.Agent$Client.<init>(Lorg/apache/thrift/protocol/TProtocol;)V
at com.uber.jaeger.senders.UdpSender.<init>(UdpSender.java:47)
at com.uber.jaeger.Configuration$SenderConfiguration.getSender(Configuration.java:609)
at com.uber.jaeger.Configuration$ReporterConfiguration.getReporter(Configuration.java:472)
at com.uber.jaeger.Configuration$ReporterConfiguration.access$100(Configuration.java:417)
at com.uber.jaeger.Configuration.getTracerBuilder(Configuration.java:228)
at com.uber.jaeger.Configuration.getTracer(Configuration.java:241)
at com.uber.jaeger.tracerresolver.JaegerTracerResolver.resolve(JaegerTracerResolver.java:25)
at io.opentracing.contrib.tracerresolver.TracerResolver.resolveTracer(TracerResolver.java:75)
```

Probably problem that class ` UdpSender` is located in `jaeger-core` jar with dependencies
on not shaded `org.apache.thrift` package

**Comment by ror6ax** [comment]
Hi guys. It looks as this is the problem that blocks @malafeev from making linkerd compatible with OpenTracing. Is there some update to the status here? Some help needed?

**Comment by objectiser** [comment]
@malafeev The problem with `jaeger-core` being dependent upon non-shaded thrift should now be fixed in #374 - awaiting next release. So would be worth trying again once the next release is out.

**Comment by malafeev** [comment]
great news @objectiser 
thanks

**Comment by jpkrohling** [comment]
I'm closing this, as it seems that this can be achieved by the command @pavolloffay mentioned. If a fat jar with the TracerResolver artifact is still wanted, feel free to reopen this.
