### ISSUE TITLE
Remote reporter index out of range exception

### ISSUE THREAD

**Issue by savioteles** [jaegertracing/jaeger-client-java#364]
I'm using the Jaeger java client 0.24.0 with RemoteReporter and UdpSender.
```
new Tracer.Builder("teste", new RemoteReporter(new UdpSender("localhost", 6831, messageMaxBytes), 1, 100, new Metrics(new StatsFactoryImpl(new NullStatsReporter()))), new ProbabilisticSampler(1.0)).build();
```

But the following Exception is thrown after append spans:

```
java.lang.ArrayIndexOutOfBoundsException: -2
	at org.apache.thrift.ShortStack.pop(ShortStack.java:36)
	at org.apache.thrift.protocol.TCompactProtocol.writeStructEnd(TCompactProtocol.java:220)
	at com.uber.jaeger.thriftjava.Batch$BatchStandardScheme.write(Batch.java:503)
	at com.uber.jaeger.thriftjava.Batch$BatchStandardScheme.write(Batch.java:430)
	at com.uber.jaeger.thriftjava.Batch.write(Batch.java:367)
	at com.uber.jaeger.agent.thrift.Agent$emitBatch_args$emitBatch_argsStandardScheme.write(Agent.java:1049)
	at com.uber.jaeger.agent.thrift.Agent$emitBatch_args$emitBatch_argsStandardScheme.write(Agent.java:1011)
	at com.uber.jaeger.agent.thrift.Agent$emitBatch_args.write(Agent.java:962)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:63)
	at com.uber.jaeger.agent.thrift.Agent$Client.send_emitBatch(Agent.java:97)
	at com.uber.jaeger.agent.thrift.Agent$Client.emitBatch(Agent.java:90)
	at com.uber.jaeger.senders.UdpSender.send(UdpSender.java:52)
	at com.uber.jaeger.senders.ThriftSender.flush(ThriftSender.java:103)
	at com.uber.jaeger.reporters.RemoteReporter$FlushCommand.execute(RemoteReporter.java:156)
	at com.uber.jaeger.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:175)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by jpkrohling** [comment]
@chandresh-pancholi it's yours. Start with a unit test, to make sure the problem still exists.

**Comment by chandresh-pancholi** [comment]
Tried reproducing this issue with version 1.0.0. The way to create JaegerTracer is changed from 0.24.0 to 1.0.0.

**Test code**
```
Configuration.SamplerConfiguration samplerConfig = Configuration.SamplerConfiguration.fromEnv()
            .withType(ProbabilisticSampler.TYPE)
            .withParam(1);

    Configuration.SenderConfiguration senderConfiguration = Configuration.SenderConfiguration.fromEnv().withAgentHost("localhost").withAgentPort(6831);
    Configuration.ReporterConfiguration reporterConfiguration = Configuration.ReporterConfiguration.fromEnv().withSender(senderConfiguration).withLogSpans(true);

    NoopMetricsFactory metricsFactory = new NoopMetricsFactory();
    Configuration config = new Configuration("test")
            .withSampler(samplerConfig)
            .withReporter(reporterConfiguration)
            .withMetricsFactory(metricsFactory);
    
    return config.getTracer();
```
