### ISSUE TITLE
getTracer() fails when the UDP socket hostname isn't resolvable

### ISSUE THREAD

**Issue by rbtcollins** [jaegertracing/jaeger-client-java#369]
We had this backtrace recently when a developer had a bad minikube configuration.
```Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.RuntimeException: TUDPTransport cannot connect:
    at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.newThriftUdpClient(ThriftUdpTransport.java:57)
    at com.uber.jaeger.senders.UdpSender.<init>(UdpSender.java:54)
    at com.uber.jaeger.Configuration$ReporterConfiguration.getSender(Configuration.java:328)
    at com.uber.jaeger.Configuration$ReporterConfiguration.getReporter(Configuration.java:335)
    at com.uber.jaeger.Configuration$ReporterConfiguration.access$000(Configuration.java:282)
    at com.uber.jaeger.Configuration.getTracerBuilder(Configuration.java:162)
    at com.uber.jaeger.Configuration.getTracer(Configuration.java:172)
...
Caused by: java.net.SocketException: Unresolved address
    at java.net.DatagramSocket.connect(DatagramSocket.java:493)
    at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.newThriftUdpClient(ThriftUdpTransport.java:55)
    ... 19 more
```

Now, for production contexts I can get behind 'broken configs should stop the program', but for developer contexts logging a message would be quite ok. A further aspect is whether the brokenness is actually broken, or transient.

For UDP protocols we cannot tell if the other end is running or not, so we don't know if the endpoint address and port are correct or not in general. Stopping therefore when they are broken in a specific way doesn't seem useful to me: we have to depend on other mechanisms to determine correctness in prod *no matter what*. That makes this qualitatively different to e.g. bad sampler configurations.

e.g. It might be nice to not throw RuntimeError for this at all, and just log it.

**Comment by yurishkuro** [comment]
Is the issue here simply that there was nothing listening on the UDP port or that the address was incorrect (like non-existent host name)?

**Comment by rbtcollins** [comment]
unresolvable hostname. The config we use is a lookup of the k8s minion a pod is running on, which is resolvable everywhere - except minikube from time to time.

**Comment by yurishkuro** [comment]
So I can't say I have strong arguments in favor of exception vs. log-only, so my suggestion would be to not make that decision and just add a config property controlling this behavior. By default it will throw exception, which could be converted into a log-only action with a boolean flag.

**Comment by jpkrohling** [comment]
I like @yurishkuro's solution. In general, we should try to avoid throwing exceptions and catch configuration problems early on, but I'm not sure we can control this case. 

So, we have to catch it and "do something". Either we log the stack trace all the time, polluting the target's log file, or we just add a WARN to the log whenever we see the exception, potentially hiding the root cause from the operator.

The flag to decide what the client should do sounds like a good compromise :)
