### ISSUE TITLE
Failing on initial connection

### ISSUE THREAD

**Issue by huntc** [jaegertracing/jaeger-client-java#382]
The client appears to fail when there is no Jaeger collector available.

There's nothing declared for `tracerConfig.getTracer` that states an exception can be thrown if there are connectivity problems. It is also quite reasonable for Jaeger's server to not be available - particularly given race conditions in a target environment where Jaeger has been launched but is not yet ready.

Thoughts?

Here's the relevant stack trace:

```
Caused by: java.lang.RuntimeException: TUDPTransport cannot connect: 
	at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.newThriftUdpClient(ThriftUdpTransport.java:49)
	at com.uber.jaeger.senders.UdpSender.<init>(UdpSender.java:59)
	at com.uber.jaeger.Configuration$SenderConfiguration.getSender(Configuration.java:739)
	at com.uber.jaeger.Configuration$ReporterConfiguration.getReporter(Configuration.java:573)
	at com.uber.jaeger.Configuration$ReporterConfiguration.access$100(Configuration.java:491)
	at com.uber.jaeger.Configuration.getTracerBuilder(Configuration.java:232)
	at com.uber.jaeger.Configuration.getTracer(Configuration.java:248)
	at com.github.huntc.lora.server.GatewayServer$$anon$1.preStart(GatewayServer.scala:115)
	at akka.actor.Actor.aroundPreStart(Actor.scala:528)
	at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
	at com.github.huntc.lora.server.GatewayServer$$anon$1.aroundPreStart(GatewayServer.scala:66)
	at akka.actor.ActorCell.create(ActorCell.scala:654)
	... 9 common frames omitted
Caused by: java.net.SocketException: Unresolved address
	at java.net.DatagramSocket.connect(DatagramSocket.java:493)
	at com.uber.jaeger.reporters.protocols.ThriftUdpTransport.newThriftUdpClient(ThriftUdpTransport.java:47)
	... 20 common frames omitted
```

**Comment by jpkrohling** [comment]
This should *not* happen. Sounds like this is failing at the DNS level. Can you confirm the collector is indeed remote and that you are specifying a hostname? Could you try specifying the host's IP instead, just to confirm?

**Comment by huntc** [comment]
The host is 127.0.0.1 and the connection is attempted from within a Docker container. 

I think that a very basic issue is that a UDP connection is established during the building of configuration.

**Comment by huntc** [comment]
Actually it could be localhost. I’m away from the code at the moment so I’ll get back to you.

**Comment by jpkrohling** [comment]
I would be interested in knowing the exact configuration for your tracer. This way, I can reproduce and fix the issue :)

**Comment by huntc** [comment]
Here are the values I used:

```
    # The host of the Jaeger agent
    agent-host         = 127.0.0.1

    # The port of the Jaeger agent
    agent-port         = 6831
```

Again, was from within a Docker container. HTH.

**Comment by jpkrohling** [comment]
@huntc I don't think I'll have the time for the next couple weeks to fix this. Would you be willing to contribute a fix?
