### ISSUE TITLE
Zipkin reporter broken due to `InternalHttpClient declares multiple JSON fields named log`

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#488]
## Requirement - what kind of business use case are you trying to solve?

Send data to Zipkin backend

## Problem - what in Jaeger blocks you from solving the requirement?

The following happens on v0.30.0 and newer. Not tested with previous versions.

```
2018-07-12 17:11:02.650  INFO 13455 --- [nio-8280-exec-1] i.j.internal.reporters.LoggingReporter   : Span reported: 8703f12860136426:a9f946e2cf131bee:8703f12860136426:1 - GET
2018-07-12 17:11:02.807 ERROR 13455 --- [nio-8280-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

java.lang.IllegalArgumentException: class org.apache.http.impl.client.InternalHttpClient declares multiple JSON fields named log
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:170) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.getAdapter(Gson.java:423) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208) ~[gson-2.8.2.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:669) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:648) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:603) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.toJson(Gson.java:583) ~[gson-2.8.2.jar:na]
	at io.jaegertracing.zipkin.internal.V2SpanConverter.buildAnnotations(V2SpanConverter.java:87) ~[jaeger-zipkin-0.30.2-SNAPSHOT.jar:0.30.2-SNAPSHOT]
	at io.jaegertracing.zipkin.internal.V2SpanConverter.convertSpan(V2SpanConverter.java:58) ~[jaeger-zipkin-0.30.2-SNAPSHOT.jar:0.30.2-SNAPSHOT]
	at io.jaegertracing.zipkin.ZipkinV2Reporter.report(ZipkinV2Reporter.java:35) ~[jaeger-zipkin-0.30.2-SNAPSHOT.jar:0.30.2-SNAPSHOT]
	at io.jaegertracing.internal.reporters.CompositeReporter.report(CompositeReporter.java:37) ~[jaeger-core-0.30.2-SNAPSHOT.jar:0.30.2-SNAPSHOT]
	at io.jaegertracing.internal.JaegerTracer.reportSpan(JaegerTracer.java:161) ~[jaeger-core-0.30.2-SNAPSHOT.jar:0.30.2-SNAPSHOT]
```

Reproducer, using the [Customer service from the Red Hat Developer Demos' Istio Tutorial](https://github.com/redhat-developer-demos/istio-tutorial/blob/master/customer/java/springboot/src/main/java/com/redhat/developer/demos/customer/CustomerApplication.java)

```java
	@Bean
	public Tracer tracer() {
        if (null == tracer) {
            ZipkinV2Reporter zipkinReporter = new ZipkinV2Reporter(AsyncReporter.create(URLConnectionSender.create("http://localhost:9411/api/v2/spans")));
            CompositeReporter compositeReporter = new CompositeReporter(zipkinReporter, new LoggingReporter());
            tracer = new JaegerTracer.Builder("service").withSampler(new ConstSampler(true)).withReporter(compositeReporter).build();

            System.out.println("Tracer: " + tracer);
        }

		return tracer;
	}
```

cc @pavolloffay

**Comment by jpkrohling** [comment]
This might be a false positive. I just tried with a very basic application and I got it working:

![image](https://user-images.githubusercontent.com/13387/42647151-6be02f98-8603-11e8-8cce-a0bab10aa819.png)
