### ISSUE TITLE
Warn/Crash when RemoteReporter QueueProcessor crashes

### ISSUE THREAD

**Issue by dignati** [jaegertracing/jaeger-client-java#590]
We are using the jaeger-client from Clojure and due to programmer error we got the following stack trace:

```
java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.String 
	at io.jaegertracing.thrift.internal.reporters.protocols.JaegerThriftSpanConverter.buildTags(JaegerThriftSpanConverter.java:98)
	at io.jaegertracing.thrift.internal.reporters.protocols.JaegerThriftSpanConverter.buildLogs(JaegerThriftSpanConverter.java:80)
	at io.jaegertracing.thrift.internal.reporters.protocols.JaegerThriftSpanConverter.convertSpan(JaegerThriftSpanConverter.java:58)
	at io.jaegertracing.thrift.internal.senders.ThriftSender.append(ThriftSender.java:55) 
	at io.jaegertracing.internal.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:140) 
	at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:173) 
	at java.lang.Thread.run(Thread.java:748)
```

It would be nice if we jaegertracing could either log warnings or crash when this (or something similar) happens, instead of silently stopping to work because there is no QueueProcessor. We only caught this because we set a default UncaughExceptionHandler for all threads.

**Comment by jpkrohling** [comment]
Would you be willing to send a PR with a proposal? The best place would probably be around the `QueueProcessor#run` method.

**Comment by yurishkuro** [comment]
Sounds reasonable. Would you like to post a PR?

**Comment by dignati** [comment]
AFAICT this change from 2016 changed changed it so that QueueProcessor only handles InterruptedException:  https://github.com/jaegertracing/jaeger-client-java/pull/19/files#diff-a214ac884be7016db64feae8ddc15ab6R161

I would propose to revert it so that we catch all Exceptions again. If you agree I can open a PR. A different approach would be to set a uncaughtExceptionHandler on the queueProcessorThread that logs a warning.
