### ISSUE TITLE
Random java.lang.NoClassDefFoundError(s) with different classes

### ISSUE THREAD

**Issue by stmlange** [jaegertracing/jaeger-client-java#593]
## Problem - what in Jaeger blocks you from solving the requirement?
Hello,
currently using jaeger to find bottle necks in an application that launches multiple sub tasks that may or may not depend on each other (sub tasks can run in parallel). Before launching the sub-tasks a "root"-span is created. When closing this span at the end of running all tasks I randomly get a `java.lang.NoClassDefFoundError`. The current workaround is to implicitly use `Class.forName("io.jaegertracing.thriftjava.Batch");` or whatever class could not be found after finishing the "root" spawn via `rootSpan.finish();`. This manually hacky solution now consist of three classes and is still growing. This simply starts to smell wrong for me and at this stage, I would highly appreciate further input on how this could be fixed properly, instead of manually listing more and more classes that could not be found.

### Current set of dependencies:
```
+--- io.opentracing:opentracing-api:0.31.0
+--- io.opentracing:opentracing-util:0.31.0
|    +--- io.opentracing:opentracing-api:0.31.0
|    \--- io.opentracing:opentracing-noop:0.31.0
|         \--- io.opentracing:opentracing-api:0.31.0
+--- io.jaegertracing:jaeger-client:0.33.1
|    +--- io.jaegertracing:jaeger-thrift:0.33.1
|    |    +--- io.jaegertracing:jaeger-core:0.33.1
|    |    |    +--- io.opentracing:opentracing-api:0.31.0
|    |    |    +--- io.opentracing:opentracing-util:0.31.0 (*)
|    |    |    +--- com.google.code.gson:gson:2.8.2
|    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.apache.thrift:libthrift:0.11.0
|    |    |    +--- org.slf4j:slf4j-api:1.7.12 -> 1.7.25
|    |    |    +--- org.apache.httpcomponents:httpclient:4.4.1
|    |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.1
|    |    |    |    +--- commons-logging:commons-logging:1.2
|    |    |    |    \--- commons-codec:commons-codec:1.9
|    |    |    \--- org.apache.httpcomponents:httpcore:4.4.1
|    |    \--- com.squareup.okhttp3:okhttp:3.9.0
|    |         \--- com.squareup.okio:okio:1.13.0
|    +--- io.jaegertracing:jaeger-core:0.33.1 (*)
|    \--- io.jaegertracing:jaeger-tracerresolver:0.33.1
|         +--- io.jaegertracing:jaeger-core:0.33.1 (*)
|         \--- io.opentracing.contrib:opentracing-tracerresolver:0.1.5
|              \--- io.opentracing:opentracing-api:0.31.0
```

### Currently affected:
- io.jaegertracing.internal.reporters.RemoteReporter$CloseCommand
- io.jaegertracing.thriftjava.Batch
- io.jaegertracing.agent.thrift.Agent$emitBatch_args
- ...ongoing

### Example 1
```
Exception in thread "Thread-12" java.lang.NoClassDefFoundError: io/jaegertracing/thriftjava/Batch
        at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:64)
        at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:110)
        at io.jaegertracing.thrift.internal.senders.ThriftSender.close(ThriftSender.java:122)
        at io.jaegertracing.thrift.internal.senders.UdpSender.close(UdpSender.java:73)
        at io.jaegertracing.internal.reporters.RemoteReporter.close(RemoteReporter.java:103)
        at io.jaegertracing.internal.JaegerTracer.close(JaegerTracer.java:216)
        at io.jaegertracing.internal.JaegerTracer$1.run(JaegerTracer.java:130)
Caused by: java.lang.ClassNotFoundException: io.jaegertracing.thriftjava.Batch
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```
### Example 2

```
Exception in thread "Thread-10" java.lang.NoClassDefFoundError: io/jaegertracing/agent/thrift/Agent$emitBatch_args
        at io.jaegertracing.agent.thrift.Agent$Client.send_emitBatch(Agent.java:68)
        at io.jaegertracing.agent.thrift.Agent$Client.emitBatch(Agent.java:63)
        at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:64)
        at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:110)
        at io.jaegertracing.thrift.internal.senders.ThriftSender.close(ThriftSender.java:122)
        at io.jaegertracing.thrift.internal.senders.UdpSender.close(UdpSender.java:73)
        at io.jaegertracing.internal.reporters.RemoteReporter.close(RemoteReporter.java:103)
        at io.jaegertracing.internal.JaegerTracer.close(JaegerTracer.java:216)
        at io.jaegertracing.internal.JaegerTracer$1.run(JaegerTracer.java:130)
  Caused by: java.lang.ClassNotFoundException: io.jaegertracing.agent.thrift.Agent$emitBatch_args
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

### Current workaround
As outlined above, using `Class.forName("io.jaegertracing.thriftjava.Batch");` after  `rootSpan.finish();` gets rid of the ` java.lang.NoClassDefFoundError: io/jaegertracing/thriftjava/Batch` problem.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Some guidance to avoid java.lang.NoClassDefFoundError(s) problems, without listing every class manually :-)

## Seems related to
- https://github.com/jaegertracing/jaeger-client-java/issues/494
- https://github.com/jaegertracing/jaeger-client-java/issues/499

**Comment by jpkrohling** [comment]
It doesn't seem like you are having problems with only the classes from the Thrift module, so, I'm not that confident that #494 or #499 are relevant.

Some questions to help us diagnose the problem:

1. Are you able to provide a reproducer?
1. Do you get this when your application is under heavy load, or do you get this also when enough memory and CPU is available?
1. How's your application deployed? Is it using a single class loader, like typical Spring Boot applications, or are you using an application server, possibly with more applications deployed on the same server?

**Comment by stmlange** [comment]
Hi,
thank you for your feedback.
1. No, currently I'm unable to reproduce the issue reliable. The issue appears to be random.
2. The issue pops up when there is no load, as well when there is "heavy" load. It does not seem to make a difference what I ask my application do to (e.g. running a leight weight task or running a "heavy" task can trigger the "problem"). Furthermore I haven't seen any relation in terms of "memory and CPU" availability.
3. That's where the tricky part begins :-) On a high level the application can be seen as a standalone binary that is deployed on a cloud (linux only) infrastructure like environment with a distributed file system. Usually to start it, I ssh to a personal "jump-host". The "jump-host" can either do tasks locally, or dispatch them to a compute-node. The root-span is created and closed by the "jump-host". Technically there can be many applications running in parallel on a single "jump-host", but that is under my control. Furthermore I can control if I want to "dispatch" tasks to different nodes. It currently does not seem to make a difference if I just run locally or "distributed". From my knowledge we use the "ClassLoader.getSystemClassLoader()" - so not sure if this is something special. Also not sure if this could be related, but in the past there was another problem with classloading that was blamed to be based on some "older libc libraries" (see https://github.com/luben/zstd-jni/issues/60 fur further information). Not sure how I could verify if this is somewhat related to this - any advice is welcome.

**Comment by jpkrohling** [comment]
> On a high level the application can be seen as a standalone binary that is deployed on a cloud

Am I right to assume that you are running on a custom JVM then? Unfortunately, it's very hard to diagnose the problem with the information you provided and without a reproducer. If you can provide a PR that fixes the problem for you without causing bad side-effects to the common case, we could certainly consider merging it.
