### ISSUE TITLE
NPE when running Jaeger in GraalVM with Micronaut

### ISSUE THREAD

**Issue by ilopmar** [jaegertracing/jaeger-client-java#600]
I'm trying to create a Micronaut application with Jaeger support. I'm able to build the native image but the application fails with a NPE.

To reproduce the issue:

- `git clone https://github.com/ilopmar/micronaut-jaeger-graal`
- `cd micronaut-jaeger-graal`
- `git checkout workaround`
- Use latest GraalVM from master branch (it won't work with RC13)
- `./build-native-image.sh`
- `./mn-jaeger-graal`

Error:
```
$ ./mn-jaeger-graal 
17:01:18.460 [main] DEBUG i.j.t.i.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
17:01:18.461 [main] DEBUG i.j.internal.senders.SenderResolver - Using sender UdpSender()
Exception in thread "Timer-0" java.lang.NullPointerException
	at io.jaegertracing.internal.samplers.RemoteControlledSampler.updateSampler(RemoteControlledSampler.java:89)
	at io.jaegertracing.internal.samplers.RemoteControlledSampler$1.run(RemoteControlledSampler.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
17:01:18.503 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 59ms. Server Running: http://localhost:8080
Exception in thread "jaeger.RemoteReporter-FlushTimer" java.lang.NullPointerException
	at io.jaegertracing.internal.reporters.RemoteReporter.flush(RemoteReporter.java:114)
	at io.jaegertracing.internal.reporters.RemoteReporter$1.run(RemoteReporter.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Comment by yurishkuro** [comment]
which  version of jaeger client? the line numbers don't match with master.

**Comment by ilopmar** [comment]
I'm sorry. Version is `0.31.0`

**Comment by yurishkuro** [comment]
in v0.31.0, `RemoteControlledSampler.java:89`, is `try {`, doesn't look right.

You may be in a better position to troubleshoot it to see which component is not configured. The other exception on `RemoteReporter.java:114` is no metric reporting, so perhaps somehow you instantiated reporter with null metrics.

**Comment by ilopmar** [comment]
Thanks for you quick reply!

I've tried with `0.33.1` and the result is the same:
```
$ ./mn-jaeger-graal 
18:08:48.880 [main] DEBUG i.j.t.i.senders.ThriftSenderFactory - Using the UDP Sender to send spans to the agent.
18:08:48.881 [main] DEBUG i.j.internal.senders.SenderResolver - Using sender UdpSender()
Exception in thread "Timer-0" java.lang.NullPointerException
	at io.jaegertracing.internal.samplers.RemoteControlledSampler.updateSampler(RemoteControlledSampler.java:89)
	at io.jaegertracing.internal.samplers.RemoteControlledSampler$1.run(RemoteControlledSampler.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
18:08:48.903 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 47ms. Server Running: http://localhost:8080
Exception in thread "jaeger.RemoteReporter-FlushTimer" java.lang.NullPointerException
	at io.jaegertracing.internal.reporters.RemoteReporter.flush(RemoteReporter.java:114)
	at io.jaegertracing.internal.reporters.RemoteReporter$1.run(RemoteReporter.java:70)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:481)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

Can the line mismatch happen because of lombok? I'm opening directly the file in IntelliJ and there is an error message: _Library source does not match the bytecode for class RemoteControlledSampler_. I can show a diff:
![image](https://user-images.githubusercontent.com/559192/53900068-ff2e8e00-403b-11e9-859e-99c998b7f6c0.png)


Regarding the error, I forgot to say that the application works fine if I start it using the JVM. You can easily reproduce the right behavior with:
- Start Jaeger with docker: `docker run -it --rm   -e COLLECTOR_ZIPKIN_HTTP_PORT=9411   -p 5775:5775/udp   -p 6831:6831/udp   -p 6832:/udp   -p 5778:5778   -p 16686:16686   -p 14268:14268   -p 9411:9411   jaegertracing/all-in-one:1.6`
- `./gradlew run`
- `curl localhost:8080/hello/Micronaut`

Then, in the UI you can see the trace:
![image](https://user-images.githubusercontent.com/559192/53899993-c8f10e80-403b-11e9-8b94-921b761e719d.png)

So this issue happens only when running the application with GraalVM. Do you have any specific support for Graal?

**Comment by yurishkuro** [comment]
I doubt it is related to Graal that much, more likely to how you instantiate the tracer. In the repo you linked I did not see any code that actually instantiates Jaeger tracer.

I am not aware of lombok messing up line numbers in the original source code (that would be pretty lousy behavior).

**Comment by objectiser** [comment]
Not sure if it will help, but Red Hat have just announced a [new project ](https://quarkus.io/) that includes OpenTracing support with [Jaeger as the default tracer](https://quarkus.io/extensions/#observability), based on GraalVM.

There is a known issue using the [UdpSender](https://github.com/quarkusio/quarkus/issues/484) in native mode - however the HttpServer works. I am hoping to look into that sometime next week.

I haven't used graalvm directly, but when I was working on the OT/Jaeger support in Quarkus, I was getting NPE due to no `MetricsFactory`. I had to [substitute a method on the Configuration class](https://github.com/quarkusio/quarkus/pull/472/files#diff-1877d3d4c6098f94055c65f3053d164f) with `NoopMetricsFactory` initially and later with a MicroProfile-Metrics based factory.

**Comment by pavolloffay** [comment]
@objectiser is the UDP sender fixed in Quarkus?

**Comment by objectiser** [comment]
No unfortunately - still need to look into it.

**Comment by objectiser** [comment]
Sorry forgot to update this issue - in Quarkus the issue with using the UdpSender on graalvm seemed to go away https://github.com/quarkusio/quarkus/pull/2304 - however this only occurred with a compiled native executable.
