### ISSUE TITLE
Failed to flush spans

### ISSUE THREAD

**Issue by amisiuryk** [jaegertracing/jaeger-client-java#767]
Hello, I have upgraded my jaeger-client from version 1.2.0 to 1.4.0. And after that I received the following errors:
```
WARN 28713 --- [-QueueProcessor] i.j.internal.reporters.RemoteReporter    traceId: '' : FlushCommand execution failed! Repeated errors of this command will not be logged.

io.jaegertracing.internal.exceptions.SenderException: Failed to flush spans.
	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:115) ~[jaeger-thrift-1.4.0.jar:1.4.0]
	at io.jaegertracing.internal.reporters.RemoteReporter$FlushCommand.execute(RemoteReporter.java:160) ~[jaeger-core-1.4.0.jar:1.4.0]
	at io.jaegertracing.internal.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:182) ~[jaeger-core-1.4.0.jar:1.4.0]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: io.jaegertracing.internal.exceptions.SenderException: Could not send 1 spans
	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:69) ~[jaeger-thrift-1.4.0.jar:1.4.0]
	at io.jaegertracing.thrift.internal.senders.ThriftSender.flush(ThriftSender.java:113) ~[jaeger-thrift-1.4.0.jar:1.4.0]
	... 3 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
Caused by: io.jaegertracing.internal.exceptions.SenderException: Could not send 1 spans

	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) ~[okhttp-3.14.9.jar:na]
Caused by: java.net.SocketTimeoutException: connect timed out

	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:na]
	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:67) ~[jaeger-thrift-1.4.0.jar:1.4.0]
	... 4 common frames omitted

```
The interesting point that client uses okhttp 4.2.2 but spring-boot overrides it to 3.14.9 as you can notice in stacktrace above.
I have forced okhttp version to 4.2.2 and 4.9.0 neither doesn't help.
The default connectionTime in OkHttpClient is set to 10 seconds. Also, spans are tracked but a lot of these warnings with stacktrace.

**Comment by naveedyahyazadeh** [comment]
Were you able to come up with a solution for this issue? I'm dealing with something similar myself 😅
